export type Profession =
  | "Physical Therapist"
  | "Dental Hygienist"
  | "Nurse Practitioner"
  | "Physician Assistant"
  | "Physician"
  | "Registered Nurse"
  | "Occupational Therapist"
  | "Home Health Aide"
  | "Diagnostic Medical Sonographer"
  | "Licensed Practical or Licensed Vocational Nurse"
  | "Physical Therapist Assistant"
  | "Dental Assistant"
  | "Medical Assistant"
  | "Medical or Clinical Laboratory Technician"
  | "Pharmacist"
  | "Surgeon"
  | "Radiologic Technologist"
  | "Surgical Technologist"
  | "Dentist"
  | "Emergency Medical Technician/Paramedic"
  | "Nursing Assistant"
  | "Family Physician or General Practitioner"
  | "Speech-language Pathologists"
  | "Occupational Therapy Assistant"
  | "Anesthesiologist"
  | "Medical Records or Health Information Technician"
  | "Nurse Anesthetist"
  | "Cardiovascular Technologist or Technician"
  | "Phlebotomists"
  | "Pharmacy Technician"
  | "Athletic Trainer"
  | "Massage Therapist"
  | "Optometrist"
  | "Respiratory Therapists"
  | "Veterinary Technologist or Technician"
  | "Physical Therapist Aide"
  | "Chiropractors"
  | "Genetic Counselors"
  | "Dietitian/Nutritionist"
  | "Optician"
  | "Internist, General"
  | "Audiologist"
  | "Veterinarian"
  | "MRI Technologist"
  | "Ophthalmic Laboratory Technician"
  | "Radiation Therapist"
  | "Pediatricians"
  | "Nuclear Medicine Technologist"
  | "Orthotist or Prosthetist"
  | "Psychiatrist";
export const SALT_ROUND: number = 10;
export const IMAGE = "crazy";
export const POST_IMAGE = "cool";
